services:
  mongodb:
    container_name: ChatAppMongoDB
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=db'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
    ports:
      - '27017'
  postgres:
    container_name: ChatAppPostgresSQL
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'

